import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import RouteLoader from "@/components/RouteLoader";
import Head from "next/head"; // ✅ Import Head

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ✅ Add Head here */}
        <Head>
          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#084887" />
          <link rel="apple-touch-icon" href="/logo.webp" />
        </Head>

        <RouteLoader />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
